hmcts/wa-task-configuration-template

- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/RWA-728
> add IT for the _DUMMY_makeAnApplication103

- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/RWA-728
> add IT for the _DUMMY_makeAnApplication104

- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/RWA-728
> add IT for the _DUMMY_makeAnApplication102

- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-728
> add IT for the _DUMMY_makeAnApplication107 and requestRespondentEvidence

- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RWA-722
feat:Remove group from dmn
```
[ ] Yes
[ ] No
```
> feat:Remove group from dmn(RWA-722)

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-924
Add case access categories in dmn
```
[ ] Yes
[ ] No
```
> feat:Add case access categories in dmn(RWA-924)

- charts/wa-task-configuration-template/Chart.yaml
up the java chart version
```
[ ] Yes
[ ] No
```
> Refactor:up the java chart version

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-839
RWA-839 NewTaskAndVariables
```
[ ] Yes
[X] No
```
> RWA-839-NewTaskAndVariables

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1088
Added column for reconfiguration
```
[ ] Yes
[ ] No
```
> RWA-1088 can reconfigure

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1107
new rules were added for Specific and Challenged Access into ```wa-task-permissions-wa-wacasetype.dmn```
```
[ ] Yes
[X] No
```
> RWA-1107-wa-task-permissions-wa-wacasetype-dmn

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1438
CVE-2022-22970, CVE-2022-22971, CVE-2022-29885 dependency upgrade, CVE-2016-1000027 supression
```
[ ] Yes
[x] No
```
> CVE(s) fixes

- src/main/resources/wa-task-completion-wa-wacasetype.dmn
- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1482
```
[ ] Yes
[X] No
```
> RWA-1482-configuration and completion dmn changes

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1482
```
[ ] Yes
[X] No
```
> RWA-1482-add a new test case for additional properties

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1325
Priority
```
[ ] Yes
[x] No
```
> Added priority

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1362
feat:Add hearing details in dmn (RWA-1362)
```
[ ] Yes
[ ] No
```
> feat:Add hearing details in dmn (RWA-1362)

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1579
upgraded tomcat and supressed false positive vulnerabilities
```
[ ] Yes
[x] No
```
> RWA-1579: upgraded tomcat and supressed false positive vulnerabilities

- Dockerfile
https://tools.hmcts.net/jira/browse/RWA-1343
Fix to resolve build error
```
[ ] Yes
[x] No
```
> RWA-1343 - Fix to resolve build error

- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
[RWA-1069](https://tools.hmcts.net/jira/browse/RWA-1069)
```
[ ] Yes
[x] No
```
> RWA-1069 Re-visit the CEH FTs which are marked as @Ignore

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1386
Little fix for local running
```
[ ] Yes
[x] No
```
> RWA 1386 fix for local

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
[RWA-1787
](https://tools.hmcts.net/jira/browse/RWA-1787)
Cherry pick additional properties for initiation
```
[ ] Yes
[ ] No
```
> Cherry pick additional properties for initiation(RWA-1787)

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Reverts hmcts/wa-task-configuration-template#39
> Revert "RWA-1528 - Granular Permission DMN"

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1885
RWA-1885 Remove Refer
```
[ ] Yes
[X] No
```
> RWA-1885 Remove Refer

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1528
RWA GP 1528 Granular Permission: DMN changes 
```
[ ] Yes
[X] No
```
> Rwa gp 1528

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Reverts hmcts/wa-task-configuration-template#63
> Revert "Rwa gp 1528"

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1528
RWA-1528-1899
```
[ ] Yes
[X] No
```
> RWA-1528-1899 GP

- src/main/resources/wa-task-types-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/DmnDecisionTable.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RWA-1494
```
[ ] Yes
[X] No
```
> RWA-1494-wa-task-types dmn added

- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1544
Added row for testing
```
[ ] Yes
[x] No
```
> RWA-1544 added role for complete granular permissions testing

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2036
Update tomcat 9.0.68
```
[ ] Yes
[x] No
```
> RWA-2036 - tomcat 9.0.68

- src/main/resources/wa-task-types-ia-asylum.dmn
- src/main/resources/wa-task-types-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RWA-1692
```
[ ] Yes
[X] No
```
> RWA-1692-empty task type dmn added for test

- charts/wa-task-configuration-template/Chart.yaml
Updating Chart version
```
[ ] Yes
[x] No
```
> Updating Chart version

- config/owasp/suppressions.xml
- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1768
```
[ ] Yes
[x] No
```
> Rwa 1768 2

- config/owasp/suppressions.xml
- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-1948
Changed mustBeWorkingDay to Next
```
[ ] Yes
[x] No
```
> RWA 1948 changed to Next

- Jenkinsfile_CNP
RWA-2052 Removal of Deprecated codes
```
[ ] Yes
[x] No
```
> RWA-2052 Removal of Deprecated codes

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2134
Changes
```
[ ] Yes
[x] No
```
> RWA-2134 - CVE fix

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2340
Suppress CVEs
```
[ ] Yes
[x ] No
```
> RWA-2340 Suppress CVE-2022-45688 and CVE-2020-8908

- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
see [RWA-1864](https://tools.hmcts.net/jira/browse/RWA-1864)
```
[ ] Yes
[ X] No
```
> RWA-1864 Add Task Type column

- gradle/wrapper/gradle-wrapper.properties
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RWA-2355
Gradle Upgrade to 7.6.1
```
[ ] Yes
[x] No
```
> RWA-2355: Gradle upgrade to 7.6.1

- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
[RWA-1773](https://tools.hmcts.net/jira/browse/RWA-1773)
[RWA-2407](https://tools.hmcts.net/jira/browse/RWA-2407)
[RWA-1762](https://tools.hmcts.net/jira/browse/RWA-1762)
Updated initiation to include delayuntil (
```
[ ] Yes
[ ] No
```
> Updated initiation to include delayuntil (RWA-1773)

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2430
FIX CVE-2023-28708
```
[ ] Yes
[ x ] No
```
> RWA-2430: fix CVE-2023-28708

- config/owasp/suppressions.xml
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-2312
```
[ ] Yes
[X] No
```
> RWA-2312-update permissions dmn according to R3.5

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
[RWA-2392](https://tools.hmcts.net/jira/browse/RWA-2392)
Add configurations
```
[ ] Yes
[ ] No
```
> Add configurations (RWA-2392)

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/DmnDecisionTableBaseUnitTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/DelayUntilRequest.java
[RWA-2426](https://tools.hmcts.net/jira/browse/RWA-2426)
Handle Json data type support 
```
[ ] Yes
[ ] No
```
> Handle Json data type support (RWA-2426)

- build.gradle
- charts/wa-task-configuration-template/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2845
Migrating to Workload Identity
```
[ ] Yes
[x] No
```
> RWA-2845 Migrating to Workload Identity

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2845
Upgrade json library version
```
[ ] Yes
[x] No
```
> RWA-2845 suppress CVE

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3092
```
[ ] Yes
[ X] No
```
> RWA-3092: Fix Suppressions

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3151
Extend CVE-2015-0897
Suppress CVE-2024-22243
```
[ ] Yes
[x] No
```
> RWA-3151: Add suppressions

- .gitignore
- src/main/resources/wa-task-allowed-days-wa-wacasetype.dmn
- src/main/resources/wa-task-cancellation-wa-wacasetype.dmn
- src/main/resources/wa-task-completion-wa-wacasetype.dmn
- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-initiation-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/main/resources/wa-task-types-ia-asylum.dmn
- src/main/resources/wa-task-types-wa-wacasetype.dmn
https://tools.hmcts.net/jira/browse/RWA-3152
> Adding TTL of 90 days to test DMNs

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-3142
Cannot clear nextHearingDate WA task field
```
[ ] Yes
[x] No
```
> RWA-3142 clear nextHearingDate

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-3119
added new rules to test various scenarios for additional properties
```
[ ] Yes
[x] No
```
> RWA-3119 additional property test

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-3288
Add a Functional Test to verify PRL scenario works
```
[ ] Yes
[x] No
```
> RWA-3288 Add a Functional Test to verify PRL scenario works

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3326
```
[ ] Yes
[x] No
```
> RWA-3326: Add Suppressions waiting spring boot upgrade

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3390
```
[ ] Yes
[x] No
```
> RWA-3390: Extend Suppressions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3499
```
[ ] Yes
[x] No
```
> RWA-3499: Remove Suppressions

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-3663
```
[ ] Yes
[x ] No
```
> RWA-3663: Reconfigure renovate PRs

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3521
```
[ ] Yes
[x] No
```
> RWA-3521: Upgrade dependencycheck to 10.0.2

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3598
```
[ ] Yes
[x] No
```
> RWA-3598: Remove Suppressions

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/DmnDecisionTableBaseUnitTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskAllowedDaysTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-3567
RWA-3567 - Fix sonar severity issues
```
[ ] Yes
[x] No
```
> RWA-3567 - Fix sonar severity issues

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
https://tools.hmcts.net/jira/browse/RWA-4061
add mandatory fields for task monitor tests
```
[ ] Yes
[x] No
```
> RWA-4061 add mandatory fields for task monitor tests

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/main/resources/wa-task-permissions-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-4550
updated for https://tools.hmcts.net/jira/browse/RWA-4550
```
[ ] Yes
[x] No
```
> RWA-4550 update dmn file

- src/main/resources/wa-task-configuration-wa-wacasetype.dmn
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RWA-4640 
```
[ ] Yes
[ ] No
```
> RWA-4640: Corrected the due dates in DMN's
